chore: clean up and refactor bin

diff --git a/bash/bin/lpass b/bash/bin/lpass
--- a/bash/bin/lpass
+++ b/bash/bin/lpass
@@ -1,23 +1,25 @@
 #!/usr/bin/env bash
 
+# lpass wrapper
+# if no args perform perform fzf search over lpass results
+
 lp='/opt/homebrew/bin/lpass'
 
-if (( $# )); then
-  $lp "$@"
-  exit $?
+if (($#)); then
+	$lp "$@"
+	exit $?
 fi
 
 if ! $lp status -q; then
-  printf "\e[31m\e[1mNot logged in\e[0m.\n"
-  read -r -p "Username: " user
-  $lp login "$user"
+	printf "\e[31m\e[1mNot logged in\e[0m.\n"
+	read -r -p "Username: " user
+	$lp login "$user"
 fi
 
-$lp ls --format $'\e[34;5m%ag \e[33;5m%an\e[m \e[35;5m%au\e[m \e[90;5m[id: %ai]\e[m' --color=always | \
-  sed -E -e 's/^[ \t]*//g' -e '/\[id:/!d' -e '/\[Deprecated/d' -e 's/^(.*5m) /\1None /g' | \
-  fzf --ansi --header $' <\e[33;5menter\e[m> Copy password to clipboard\n <\e[33;5mctrl-o\e[m> Output JSON' \
-  --prompt='󰑆 ' \
-  --border-label=' Lastpass ' \
-  "--bind=ctrl-o:execute@echo {} | sed 's/.*\[id: \([0-9]*\)\].*/\1/g' | xargs '$lp' show --json | jq . @+abort" \
-  "--bind=enter:execute@echo {} | sed 's/.*\[id: \([0-9]*\)\].*/\1/g' | xargs '$lp' show --password --clip @+abort"
-
+$lp ls --format $'\e[34;5m%ag \e[33;5m%an\e[m \e[35;5m%au\e[m \e[90;5m[id: %ai]\e[m' --color=always |
+	sed -E -e 's/^[ \t]*//g' -e '/\[id:/!d' -e '/\[Deprecated/d' -e 's/^(.*5m) /\1None /g' |
+	fzf --ansi --header $' <\e[33;5menter\e[m> Copy password to clipboard\n <\e[33;5mctrl-o\e[m> Output JSON' \
+		--prompt='󰑆 ' \
+		--border-label=' Lastpass ' \
+		"--bind=ctrl-o:execute@echo {} | sed 's/.*\[id: \([0-9]*\)\].*/\1/g' | xargs '$lp' show --json | jq . @+abort" \
+		"--bind=enter:execute@echo {} | sed 's/.*\[id: \([0-9]*\)\].*/\1/g' | xargs '$lp' show --password --clip @+abort"
